### ISSUE TITLE
diff.algorithm=patience not available on some systems

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/dev-sourcecode-record#22]
A candidate encountered the following exception while recording source code:
Target OS is probably Ubuntu:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
	at tdl.record.sourcecode.snapshot.PatchSnapshot.takeSnapshotFromGit(PatchSnapshot.java:23) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.snapshot.SnapshotRecorder.takePatchSnapshot(SnapshotRecorder.java:119) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.snapshot.SnapshotRecorder.takeSnapshot(SnapshotRecorder.java:104) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.snapshot.file.Writer.createSnapshotFromRecorder(Writer.java:81) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.snapshot.file.Writer.takeSnapshotWithTag(Writer.java:70) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.record.SourceCodeRecorder.doRecord(SourceCodeRecorder.java:151) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.record.SourceCodeRecorder.start(SourceCodeRecorder.java:135) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record_upload.sourcecode.SourceCodeRecordingThread.run(SourceCodeRecordingThread.java:38) ~[record-and-upload-0.0.14.jar:na]
Caused by: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:443) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:361) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:208) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:176) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:119) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at tdl.record.sourcecode.snapshot.helpers.GitHelper.exportDiff(GitHelper.java:63) ~[dev-sourcecode-record-0.0.16.jar:na]
	at tdl.record.sourcecode.snapshot.PatchSnapshot.takeSnapshotFromGit(PatchSnapshot.java:18) ~[dev-sourcecode-record-0.0.16.jar:na]
	... 7 common frames omitted
```

**Comment by julianghionoiu** [comment]
Looks like this is JGit's behaviour. On some possible newer systems, this option might not be available.

There are three steps we can take:
- [x] Reproduce the error
- [ ] Update JGit to latest version
- [x] Investigate setting an alternative diff algorithms

**Comment by julianghionoiu** [comment]
Found a reference to this problem on JGit repo: https://github.com/clj-jgit/clj-jgit/issues/21

**Comment by neomatrix369** [comment]
What command or script do they run before the program throws that error? Do I also need a place where I can upload the video (the command will need a destination location)?

**Comment by neomatrix369** [comment]
It would be great to capture system details in the user's log files, i.e. output of `uname -a`:
```
Linux xxxxxxx 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
and `cat /etc/lsb-release`

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

Atm I will have to dig out which OS version does not support that `JGit` flag

**Comment by neomatrix369** [comment]
Found another ref https://ecosystem.atlassian.net/browse/MJF-152

**Comment by neomatrix369** [comment]
Just found out https://github.com/eclipse/jgit/releases/tag/v5.0.2.201807311906-r has the implementation of the [PatienceDiff class](https://github.com/eclipse/jgit/commit/a67afbfee10ca2963f5f0f52f701376e382572e2#diff-9b938cf1036547bc0496517a1f3da392) deleted via commit https://github.com/eclipse/jgit/commit/e82cadc0dcece55ff8bad1a890bf9e3f8b802cdf

**Comment by neomatrix369** [comment]
Reproduced:
```
$ git config --global --add diff.algorithm patience     
```

Rebuild `dev-sourcecode-record` using dependency `org.eclipse.jgit:org.eclipse.jgit:5.0.2.201807311906-r`

Ran the below:
```
 java -jar build/libs/dev-sourcecode-record-0.0.17-SNAPSHOT-all.jar record --source src --output test.srcs
Enter tag name to trigger a tagged snapshot or "exit" to stop recording
18:57:55.511 [Thread-1] DEBUG org.eclipse.jgit.util.FS - readpipe [git, --version],/usr/bin
18:57:55.519 [Thread-1] DEBUG org.eclipse.jgit.util.FS - readpipe may return 'git version 2.17.0'
18:57:55.519 [Thread-1] DEBUG org.eclipse.jgit.util.FS - remaining output:

18:57:55.519 [Thread-1] DEBUG org.eclipse.jgit.util.FS - readpipe [git, config, --system, --edit],/usr/bin
18:57:55.521 [Thread-1] DEBUG org.eclipse.jgit.util.FS - readpipe may return '/etc/gitconfig'
18:57:55.522 [Thread-1] DEBUG org.eclipse.jgit.util.FS - remaining output:

18:57:55.625 [Thread-1] INFO  t.r.s.m.SourceCodeRecordingMetricsCollector - Start recording to "test.srcs"
18:57:55.625 [Thread-1] DEBUG t.r.s.m.SourceCodeRecordingMetricsCollector - Source Code snap !
18:57:56.057 [Thread-1] DEBUG t.r.s.m.SourceCodeRecordingMetricsCollector - lastSnapshotProcessingTimeNano: 432236353
18:57:56.058 [Thread-1] DEBUG t.r.s.time.SystemMonotonicTimeSource - Sleep for: 4566 millis
^C18:57:57.709 [Thread-0] INFO  t.r.s.record.SourceCodeRecorder - Stopping recording
18:57:57.710 [Thread-1] DEBUG t.r.s.m.SourceCodeRecordingMetricsCollector - Source Code snap !
18:57:57.940 [Thread-1] INFO  t.r.s.m.SourceCodeRecordingMetricsCollector - Recording stopped
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
	at tdl.record.sourcecode.RecordCommand.lambda$doRun$0(RecordCommand.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
	at tdl.record.sourcecode.snapshot.PatchSnapshot.takeSnapshotFromGit(PatchSnapshot.java:23)
	at tdl.record.sourcecode.snapshot.SnapshotRecorder.takePatchSnapshot(SnapshotRecorder.java:119)
	at tdl.record.sourcecode.snapshot.SnapshotRecorder.takeSnapshot(SnapshotRecorder.java:104)
	at tdl.record.sourcecode.snapshot.file.Writer.createSnapshotFromRecorder(Writer.java:81)
	at tdl.record.sourcecode.snapshot.file.Writer.takeSnapshotWithTag(Writer.java:70)
	at tdl.record.sourcecode.record.SourceCodeRecorder.doRecord(SourceCodeRecorder.java:151)
	at tdl.record.sourcecode.record.SourceCodeRecorder.start(SourceCodeRecorder.java:135)
	at tdl.record.sourcecode.RecordCommand.lambda$doRun$0(RecordCommand.java:59)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
	at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:138)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:374)
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:211)
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:179)
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:124)
	at tdl.record.sourcecode.snapshot.helpers.GitHelper.exportDiff(GitHelper.java:63)
	at tdl.record.sourcecode.snapshot.PatchSnapshot.takeSnapshotFromGit(PatchSnapshot.java:18)
	... 8 more
```

**Comment by julianghionoiu** [comment]
Nice one!

**Comment by neomatrix369** [comment]
Actually, it does not make a difference if we build `dev-sourcecode-record` with `4.8.0.201706111038-r` or  `5.0.2.201807311906-r`, it fails in both cases and throws the error:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience
        at tdl.record.sourcecode.snapshot.PatchSnapshot.takeSnapshotFromGit(PatchSnapshot.java:23)
<snipped>
```

**Comment by neomatrix369** [comment]
I think I have resolved the issue, and the failing tests are a sign the issue exists when config is set to `patience` I'll amend the existing tests to reproduce the issue and fix it.:

```java
java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience

	at org.eclipse.jgit.lib.Config.getEnum(Config.java:443)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:361)
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:208)
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:176)
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:119)
	at tdl.record.sourcecode.snapshot.helpers.GitHelper.exportDiff(GitHelper.java:75)
	at tdl.record.sourcecode.snapshot.helpers.DiffAlgoPatienceJGitIssueTest.exportDiffOnEmptyFiles(DiffAlgoPatienceJGitIssueTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience

	at org.eclipse.jgit.lib.Config.getEnum(Config.java:443)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:361)
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:208)
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:176)
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:119)
	at tdl.record.sourcecode.snapshot.helpers.GitHelper.exportDiff(GitHelper.java:75)
	at tdl.record.sourcecode.snapshot.helpers.DiffAlgoPatienceJGitIssueTest.applyPatch(DiffAlgoPatienceJGitIssueTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


java.lang.IllegalArgumentException: Invalid value: diff.algorithm=patience

	at org.eclipse.jgit.lib.Config.getEnum(Config.java:443)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:361)
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:208)
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:176)
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:119)
	at tdl.record.sourcecode.snapshot.helpers.GitHelper.exportDiff(GitHelper.java:75)
	at tdl.record.sourcecode.snapshot.helpers.DiffAlgoPatienceJGitIssueTest.exportPatchAndApply(DiffAlgoPatienceJGitIssueTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
