### ISSUE TITLE
Git export failure - user tzcu01

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/dev-sourcecode-record#24]
The following sourcecode recording fails the export command with an IndexOutOfBoundsException:
https://s3.eu-west-2.amazonaws.com/tdl-official-videos/CHK/tzcu01/sourcecode_20180405T111942.srcs

command
```
 java -jar dev-sourcecode-record-0.0.15-all.jar convert-to-git -i sourcecode_20180405T111942.srcs -o to_git
```

output:
```
Committing timestamp: 7222
Exception in thread "main" java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 89, Size: 88
	at tdl.record.sourcecode.ConvertToGitCommand.run(ConvertToGitCommand.java:45)
	at tdl.record.sourcecode.App.main(App.java:27)
```

Needs to be investigated

**Comment by neomatrix369** [comment]
@julianghionoiu 
Looking at this issue, narrowed it down to this block (see https://github.com/julianghionoiu/dev-sourcecode-record/blob/master/src/main/java/jgit/hack/ApplyCommandFixed.java#L181):

```java
            for (int j = 1; j < hunkLines.size(); j++) {
                String hunkLine = hunkLines.get(j);
                switch (hunkLine.charAt(0)) {
                    case ' ':
                        ensureLineContentMatchesDestination(hunkLine.substring(1), newLines, hh, pos);
                        pos++;    <=== incremented when ' ' is encountered
                        break;
                    case '-':
                        if (hh.getNewStartLine() == 0) {
                            newLines.clear();
                        } else {
                            ensureLineContentMatchesDestination(hunkLine.substring(1), newLines, hh, pos);
                            newLines.remove(hh.getNewStartLine() - 1 + pos);
                        }
                        <=== should pos be decremented when '-' is encountered?
                        break;
                    case '+':
                        newLines.add(hh.getNewStartLine() - 1 + pos,
                                hunkLine.substring(1));  <=== failing here like it says java.lang.IndexOutOfBoundsException: Index: 89, Size: 88 i.e. newLines.size() at that time is 88 and hh.getNewStartLine() - 1 + pos is evaluting to 89, and HunkHeader[96,13->81,10]
                        pos++;   <=== incremented when '+' is encountered
                        break;
                }
            }
        }
```
Left a question for case '-', the `pos` value is going out of sync when `hunkLine.charAt(0)` encounters combinations of ' ' and '+' ;

Please also explain what each of the blocks against ' ', '+' and '-' do, saves me from assuming what the code is doing or suppose to do.

Also how do you translate this `HunkHeader[96,13->81,10]`?

**Comment by neomatrix369** [comment]
It looks like there have been deletions, i.e. ~15 lines which could cause the `HunkHeader` to say that

**Comment by neomatrix369** [comment]
The line on which this action took place was the last line on `HunkHeader`, see
```
hunkLines = {java.util.ArrayList@2676}  size = 16
 0 = "@@ -96,13 +81,10 @@"
 1 = "             f_free_count -= 1"
 2 = "     total += f_count * 10"
 3 = " "
 4 = "-    # if item in GROUP_SIMPLE:"
 5 = "-    #     item"
 6 = "-    # total += skus.count("C") * 20"
 7 = "-    # total += skus.count("D") * 15"
 8 = "     for item in skus:"
 9 = "-        total += GROUP_SIMPLE2.get(item, 0)"
 10 = "+        total += GROUP_SIMPLE.get(item, 0)"
 11 = " "
 12 = "     return total"
 13 = " "
 14 = " "
 15 = "+print(checkout("1"))"   <=== error occurred when trying to process this line
```

But that line was going to be inserted somewhere in the middle of the newLines array.

**Comment by neomatrix369** [comment]
Code coverage says its only 0.3% more complex ;) - what do you reckon?
